package zzh.com.haooa.greenDao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import zzh.com.haooa.bean.UserInfoBean;

import zzh.com.haooa.bean.DepartmentBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPARTMENT_BEAN".
*/
public class DepartmentBeanDao extends AbstractDao<DepartmentBean, String> {

    public static final String TABLENAME = "DEPARTMENT_BEAN";

    /**
     * Properties of entity DepartmentBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DepartmentID = new Property(0, String.class, "departmentID", true, "DEPARTMENT_ID");
        public final static Property HxUsername = new Property(1, String.class, "HxUsername", false, "HX_USERNAME");
        public final static Property DepartmentName = new Property(2, String.class, "departmentName", false, "DEPARTMENT_NAME");
        public final static Property CreateTime = new Property(3, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(4, String.class, "updateTime", false, "UPDATE_TIME");
    }

    private DaoSession daoSession;


    public DepartmentBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DepartmentBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPARTMENT_BEAN\" (" + //
                "\"DEPARTMENT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: departmentID
                "\"HX_USERNAME\" TEXT," + // 1: HxUsername
                "\"DEPARTMENT_NAME\" TEXT," + // 2: departmentName
                "\"CREATE_TIME\" TEXT," + // 3: createTime
                "\"UPDATE_TIME\" TEXT);"); // 4: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPARTMENT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DepartmentBean entity) {
        stmt.clearBindings();
 
        String departmentID = entity.getDepartmentID();
        if (departmentID != null) {
            stmt.bindString(1, departmentID);
        }
 
        String HxUsername = entity.getHxUsername();
        if (HxUsername != null) {
            stmt.bindString(2, HxUsername);
        }
 
        String departmentName = entity.getDepartmentName();
        if (departmentName != null) {
            stmt.bindString(3, departmentName);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(5, updateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DepartmentBean entity) {
        stmt.clearBindings();
 
        String departmentID = entity.getDepartmentID();
        if (departmentID != null) {
            stmt.bindString(1, departmentID);
        }
 
        String HxUsername = entity.getHxUsername();
        if (HxUsername != null) {
            stmt.bindString(2, HxUsername);
        }
 
        String departmentName = entity.getDepartmentName();
        if (departmentName != null) {
            stmt.bindString(3, departmentName);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(5, updateTime);
        }
    }

    @Override
    protected final void attachEntity(DepartmentBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public DepartmentBean readEntity(Cursor cursor, int offset) {
        DepartmentBean entity = new DepartmentBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // departmentID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // HxUsername
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // departmentName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // createTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DepartmentBean entity, int offset) {
        entity.setDepartmentID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setHxUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDepartmentName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreateTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUpdateTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DepartmentBean entity, long rowId) {
        return entity.getDepartmentID();
    }
    
    @Override
    public String getKey(DepartmentBean entity) {
        if(entity != null) {
            return entity.getDepartmentID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DepartmentBean entity) {
        return entity.getDepartmentID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserInfoBeanDao().getAllColumns());
            builder.append(" FROM DEPARTMENT_BEAN T");
            builder.append(" LEFT JOIN USER_INFO_BEAN T0 ON T.\"HX_USERNAME\"=T0.\"HX_USERNAME\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DepartmentBean loadCurrentDeep(Cursor cursor, boolean lock) {
        DepartmentBean entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UserInfoBean user = loadCurrentOther(daoSession.getUserInfoBeanDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public DepartmentBean loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DepartmentBean> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DepartmentBean> list = new ArrayList<DepartmentBean>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DepartmentBean> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DepartmentBean> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
